</div>
</div>
</div>
<footer>
    <p>© Maquette par <a href="https://christianelagace.com" target="_blank">Christiane Lagacé</a>, inspirée du travail de
        <a href="https://www.free-css.com/free-css-templates/page5/the-hobbit"target="_blank">Arcsin</a>.</p>
    Site web par louis hince 2025
    <?php
    // Cette page ainsi que le site au complet a été réaliser par Louis Hince, inspiré de la maquette de Christianne Lagacé.
    // Plusieurs fonctions et bouts de code proviennent d'Apical.
    /**
     * Page d'accueil pour mon blogue.
     * @author lOUIS HINCE>
     */?>

</footer>
</body>
</html>