<!DOCTYPE html>
<!-- Website template by freewebsitetemplates.com -->
<html>
<head>
    <meta charset="UTF-8" />
    <title>Le centre sportif -Le ptit jesus-</title>
    <link rel="stylesheet" type="text/css" href="css/style.css" />
    <!--[if IE 9]>
    <link rel="stylesheet" type="text/css" href="css/ie9.css" />
    <![endif]-->
    <!--[if IE 7]>
    <link rel="stylesheet" type="text/css" href="css/ie7.css" />
    <![endif]-->
    <!--[if IE 6]>
    <link rel="stylesheet" type="text/css" href="css/ie6.css" />
    <![endif]-->
</head>
<body>