<div id="footer">
    <div>
        <div>
            <div id="connect">
                <span>Suivez-nous :</span>
                <a href="" target="_blank"><img src="images/icon-facebook.gif" alt="Facebook" /></a>
                <a href="" target="_blank"><img src="images/icon-twitter.gif" alt="Twitter" /></a>
            </div>
            <div class="section">
                <ul>
                    <li class="first"><a href="index.html">Accueil</a></li>
                    <li><a href="">menu 2</a></li>
                    <li><a href="">menu 3</a></li>
                </ul>
                <p>&copy; Copyright 0000. Company Name. All Rights Reserved.</p>
            </div>
        </div>
    </div>
</div>
</body>
</html>