<footer>
    <p>© Maquette par <a href="https://christianelagace.com" target="_blank">Christiane Lagacé</a>, inspirée du travail de
        <a href="https://www.free-css.com/free-css-templates/page5/the-hobbit"target="_blank">Arcsin</a>.</p>
    Site web par louis hince 2025
    <?php
    /**
     * Page d'accueil pour mon blogue.
     * @author lOUIS HINCE>
     */?>

</footer>
</body>
</html>